### PR TITLE
Renderer refactor

### PR DESCRIPTION
**Pull request by Courtsilius**
Refactoring the rendering of the UI into it's own Class, as well as moving the room configuration outside of the first person controller.

### CODE REVIEW

**Review by LouisHain — CHANGES_REQUESTED** [review]
currently the nuke splats are not in the server public folder and/or in the PR, they will break the server at checkFileExists.
The teleport is out of bounds and locks you in place.
debug in the admin panel can be enabled, but not disabled forcing you to reload the site to disable the wireframes.

**Comment by Courtsilius** [comment]
1 & 2 have been fixed. If you insist on being able to derender the debug wireframes we can do that, but I feel like currently there's not that big of a need for it, so I'd move that to a new ticket if that's OK with you.

**Review by LouisHain — APPROVED** [review]
sure, that works for me, thanks

**Comment by Courtsilius** [comment]
Created Issue #82 to keep track of this

**Pull request merged**
